server:
  port: 18080
  servlet:
    context-path: /admin
spring:
  application:
    name: genie-admin
  datasource:
    url: jdbc:mysql://127.0.0.1:3308/genie_admin?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
